/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/categorias": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ListarCategorias"];
        put?: never;
        post: operations["CriarCategoria"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/categorias/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ObterCategoria"];
        put: operations["AtualizarCategoria"];
        post?: never;
        /** @description Bloqueada (409) se a categoria tiver transações ou orçamentos. */
        delete: operations["ExcluirCategoria"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/contas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Por padrão só contas ativas. O saldo atual é calculado a partir das transações. */
        get: operations["ListarContas"];
        put?: never;
        post: operations["CriarConta"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/contas/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ObterConta"];
        /** @description Para arquivar uma conta, envie Ativa = false. */
        put: operations["AtualizarConta"];
        post?: never;
        /** @description Bloqueada (409) se a conta tiver transações; nesse caso, arquive. */
        delete: operations["ExcluirConta"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/transacoes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Filtros opcionais; `mes` exige `ano`. Ordenado da mais recente para a mais antiga. */
        get: operations["ListarTransacoes"];
        put?: never;
        post: operations["CriarTransacao"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/transacoes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ObterTransacao"];
        put: operations["AtualizarTransacao"];
        post?: never;
        delete: operations["ExcluirTransacao"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orcamentos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Todas as categorias de despesa com limite, gasto e percentual do mês (padrão: mês atual). */
        get: operations["ListarOrcamentos"];
        /** @description Cria ou atualiza o limite da categoria no mês. */
        put: operations["DefinirOrcamento"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orcamentos/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["ExcluirOrcamento"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard/resumo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Receitas, despesas e resultado do mês, e saldo das contas ativas ao fim do mês (padrão: mês atual). */
        get: operations["ObterResumo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard/gastos-por-categoria": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Despesas do mês agrupadas por categoria, da maior para a menor. */
        get: operations["ObterGastosPorCategoria"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard/evolucao": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Receitas e despesas dos últimos N meses, terminando no mês informado (padrão: mês atual). */
        get: operations["ObterEvolucao"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CategoriaDto: {
            /** Format: int32 */
            id: number;
            nome: string;
            tipo: components["schemas"]["TipoTransacao"];
            cor: string;
        };
        CategoriaInput: {
            nome: string;
            tipo: components["schemas"]["TipoTransacao"];
            cor: string;
        };
        ContaDto: {
            /** Format: int32 */
            id: number;
            nome: string;
            tipo: components["schemas"]["TipoConta"];
            /** Format: double */
            saldoInicial: number;
            ativa: boolean;
            /** Format: double */
            saldoAtual: number;
        };
        ContaInput: {
            nome: string;
            tipo: components["schemas"]["TipoConta"];
            /** Format: double */
            saldoInicial: number;
            /** @default true */
            ativa: boolean;
        };
        EvolucaoMesDto: {
            /** Format: int32 */
            ano: number;
            /** Format: int32 */
            mes: number;
            /** Format: double */
            receitas: number;
            /** Format: double */
            despesas: number;
            /** Format: double */
            resultado: number;
        };
        GastoCategoriaDto: {
            /** Format: int32 */
            categoriaId: number;
            nome: string;
            cor: string;
            /** Format: double */
            total: number;
            /** Format: double */
            percentual: number;
        };
        HttpValidationProblemDetails: {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number;
            detail?: null | string;
            instance?: null | string;
            errors?: {
                [key: string]: string[];
            };
        };
        OrcamentoDto: {
            /** Format: int32 */
            id: null | number;
            /** Format: int32 */
            categoriaId: number;
            categoriaNome: string;
            categoriaCor: string;
            /** Format: int32 */
            ano: number;
            /** Format: int32 */
            mes: number;
            /** Format: double */
            limite: null | number;
            /** Format: double */
            gasto: number;
            /** Format: double */
            percentual: null | number;
        };
        OrcamentoInput: {
            /** Format: int32 */
            categoriaId: number;
            /** Format: int32 */
            ano: number;
            /** Format: int32 */
            mes: number;
            /** Format: double */
            limite: number;
        };
        PaginaOfTransacaoDto: {
            itens: components["schemas"]["TransacaoDto"][];
            /** Format: int32 */
            numeroPagina: number;
            /** Format: int32 */
            tamanhoPagina: number;
            /** Format: int32 */
            totalItens: number;
            /** Format: int32 */
            totalPaginas?: number;
        };
        ResumoDto: {
            /** Format: int32 */
            ano: number;
            /** Format: int32 */
            mes: number;
            /** Format: double */
            saldoTotal: number;
            /** Format: double */
            receitas: number;
            /** Format: double */
            despesas: number;
            /** Format: double */
            resultado: number;
        };
        /** @enum {unknown} */
        TipoConta: "Corrente" | "Poupanca" | "Cartao" | "Carteira" | "Investimento";
        /** @enum {unknown} */
        TipoTransacao: "Receita" | "Despesa";
        TransacaoDto: {
            /** Format: int32 */
            id: number;
            descricao: string;
            /** Format: double */
            valor: number;
            tipo: components["schemas"]["TipoTransacao"];
            /** Format: date */
            data: string;
            /** Format: int32 */
            contaId: number;
            contaNome: string;
            /** Format: int32 */
            categoriaId: number;
            categoriaNome: string;
            categoriaCor: string;
            observacao: null | string;
        };
        TransacaoInput: {
            descricao: string;
            /** Format: double */
            valor: number;
            tipo: components["schemas"]["TipoTransacao"];
            /** Format: date */
            data: string;
            /** Format: int32 */
            contaId: number;
            /** Format: int32 */
            categoriaId: number;
            observacao?: null | string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    ListarCategorias: {
        parameters: {
            query?: {
                tipo?: components["schemas"]["TipoTransacao"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoriaDto"][];
                };
            };
        };
    };
    CriarCategoria: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoriaInput"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoriaDto"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
        };
    };
    ObterCategoria: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoriaDto"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AtualizarCategoria: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoriaInput"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoriaDto"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ExcluirCategoria: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ListarContas: {
        parameters: {
            query?: {
                incluirInativas?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContaDto"][];
                };
            };
        };
    };
    CriarConta: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContaInput"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContaDto"];
                };
            };
        };
    };
    ObterConta: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContaDto"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AtualizarConta: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContaInput"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContaDto"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ExcluirConta: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ListarTransacoes: {
        parameters: {
            query?: {
                ano?: number;
                mes?: number;
                contaId?: number;
                categoriaId?: number;
                tipo?: components["schemas"]["TipoTransacao"];
                pagina?: number;
                tamanhoPagina?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginaOfTransacaoDto"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
        };
    };
    CriarTransacao: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransacaoInput"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransacaoDto"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
        };
    };
    ObterTransacao: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransacaoDto"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AtualizarTransacao: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransacaoInput"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransacaoDto"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ExcluirTransacao: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ListarOrcamentos: {
        parameters: {
            query?: {
                ano?: number;
                mes?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrcamentoDto"][];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
        };
    };
    DefinirOrcamento: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrcamentoInput"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrcamentoDto"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
        };
    };
    ExcluirOrcamento: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ObterResumo: {
        parameters: {
            query?: {
                ano?: number;
                mes?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResumoDto"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
        };
    };
    ObterGastosPorCategoria: {
        parameters: {
            query?: {
                ano?: number;
                mes?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GastoCategoriaDto"][];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
        };
    };
    ObterEvolucao: {
        parameters: {
            query?: {
                ano?: number;
                mes?: number;
                meses?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvolucaoMesDto"][];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
        };
    };
}
